import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>陪诊师.com</title>
        <meta name="description" content="Generated by 猎思科技" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div className={styles.title}>
            就医找陪诊，就找91陪诊
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/小程序码.jpg"
            alt="小程序码"
            width={180}
            height={180}
            priority
          />
         
        </div>

        <div className={styles.grid}>
          <a
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              实名认证 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
             所有的陪诊师都是人名、证件一致，
            </p>
          </a>

          <a
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              隐私安全 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              严格保护客户个人隐私
            </p>
          </a>

          <a
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              培训上岗 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              严格把控服务细节，处处体现专业服务
            </p>
          </a>

          <a
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              标准流程 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              标准化的服务流程
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
